/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoreHeader: typeof import('./src/components/Core/Header/Header.vue')['default']
    PagesHomeCustomers: typeof import('./src/components/Pages/Home/Customers/Customers.vue')['default']
    PagesHomeCustomersLogo: typeof import('./src/components/Pages/Home/Customers/Logo.vue')['default']
    PagesHomeCustomersRecords: typeof import('./src/components/Pages/Home/Customers/Records.vue')['default']
    PagesHomeDomain: typeof import('./src/components/Pages/Home/Domain/index.vue')['default']
    PagesHomeHosts: typeof import('./src/components/Pages/Home/Hosts/index.vue')['default']
    PagesHomeOperation: typeof import('./src/components/Pages/Home/Operation/Operation.vue')['default']
    PagesHomeSecurity: typeof import('./src/components/Pages/Home/Security/index.vue')['default']
    PagesHomeSecurityCard: typeof import('./src/components/Pages/Home/Security/Card/Card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedContainer: typeof import('./src/components/Shared/Container/Container.vue')['default']
    SharedNavigation: typeof import('./src/components/Shared/Navigation/Navigation.vue')['default']
  }
}
