/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedContainer: typeof import('./src/components/Shared/Container/Container.vue')['default']
    SharedNavigation: typeof import('./src/components/Shared/Navigation/Navigation.vue')['default']
  }
}
